# Generated by Django 5.2.9 on 2026-01-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_globallexicalstats_lexicaldifficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseprogress',
            name='exercise_type',
            field=models.CharField(choices=[('flashcards', 'Flashcards'), ('quiz', 'Quiz'), ('antonym', 'Antonym'), ('fill-blanks', 'Fill in the Blanks')], max_length=20),
        ),
    ]
