# Generated by Django 5.2.9 on 2026-01-05 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_alter_exerciseprogress_exercise_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseprogress',
            name='exercise_type',
            field=models.CharField(choices=[('flashcards', 'Flashcards'), ('quiz', 'Quiz'), ('antonym', 'Antonym'), ('lesson-cards', 'Lesson Cards'), ('error-identification', 'Error Identification'), ('fill-blanks', 'Fill the Blanks')], max_length=20),
        ),
    ]
