# Generated by Django 5.2.9 on 2026-01-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_alter_exerciseprogress_exercise_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseprogress',
            name='cards_reviewed',
            field=models.IntegerField(blank=True, help_text='For flashcards', null=True),
        ),
        migrations.AddField(
            model_name='exerciseprogress',
            name='lessons_viewed',
            field=models.IntegerField(blank=True, help_text='For lesson cards', null=True),
        ),
        migrations.AddField(
            model_name='exerciseprogress',
            name='time_spent',
            field=models.IntegerField(default=0, help_text='Time spent in seconds'),
        ),
        migrations.AlterField(
            model_name='exerciseprogress',
            name='exercise_type',
            field=models.CharField(choices=[('flashcards', 'Flashcards (Lesson)'), ('quiz', 'What is its Closest Meaning'), ('antonym', 'Antonym of the Word'), ('lesson-cards', 'Grammar Lesson Cards'), ('error-identification', 'Error Identification'), ('fill-blanks', 'Fill the Blanks'), ('complete-sentence', 'Complete the Sentence'), ('sentence-ordering', 'Sentence Ordering'), ('passage-questions', 'Passage Questions'), ('comprehension', 'Reading Comprehension')], max_length=30),
        ),
        migrations.AlterField(
            model_name='exerciseprogress',
            name='last_difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseprogress',
            name='status',
            field=models.CharField(choices=[('not-started', 'Not Started'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('locked', 'Locked')], default='locked', max_length=20),
        ),
    ]
