# Generated by Django 5.2.9 on 2026-01-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_exerciseprogress_cards_reviewed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseprogress',
            name='exercise_type',
            field=models.CharField(choices=[('flashcards', 'Flashcards (Lesson)'), ('quiz', 'What is its Closest Meaning'), ('antonym', 'Antonym of the Word'), ('lesson-cards', 'Grammar Lesson Cards'), ('error-identification', 'Error Identification'), ('fill-blanks', 'Fill the Blanks'), ('complete-sentence', 'Complete the Sentence'), ('sentence-ordering', 'Sentence Ordering'), ('choose-sentence', 'Choose the Sentence'), ('reading-passages', 'Reading Passages'), ('summarization', 'Summarization')], max_length=30),
        ),
        migrations.AlterField(
            model_name='exerciseprogress',
            name='status',
            field=models.CharField(choices=[('not-started', 'Not Started'), ('in-progress', 'In Progress')], default='not-started', max_length=20),
        ),
    ]
