# Generated by Django 5.2.9 on 2026-01-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='provider',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('google', 'Google'), ('supabase', 'Supabase')], help_text='Authentication provider', max_length=50, null=True),
        ),
    ]
